### ISSUE TITLE
BUG024 -  Recebimento de Timeout após a requisição do Login

### ISSUE THREAD

**Issue by muriloschiler** [fga-eps-mds/2024.1-MeasureSoftGram-DOC#108]
## Descrição
   Após ser enviado as credenciais para o Login para a service , mesmo recebendo o status 200 , tem-se uma tela de "carregamento" e do  envio de um Timeout por parte da aplicação.
## Como reproduzir
   Realize o login na aplicação.
## Comportamento esperado
   Entrar na aplicação logado
## Prints
![Carregando](https://github.com/user-attachments/assets/05d8e29c-e452-4b36-b5f1-9e1315dd955d)
![Timeout](https://github.com/user-attachments/assets/cd05c6e0-dd92-4d6b-b8b2-d0a3b091cee0)

**Comment by muriloschiler** [comment]
O erro acontece mesmo apontando para a Service local,http://localhost:8080/api/v1, ou de produção , https://epsmsg.shop/api/v1/ .

**Comment by muriloschiler** [comment]
Incrivelmente fui entrar no http://localhost:3000/home/ e deu certo , horas após se tentar realizar o login pelo sistema e receber o Timeout.
Porém agora pela tela de Home, tento clicar na opção settings e obtenho o mesmo problema de Timeout.

  
![Home_Timeout](https://github.com/user-attachments/assets/479ab5c1-e308-4020-94cf-57b75b7e5b34)

**Comment by muriloschiler** [comment]
Outro comportamento estranho notado é que em nenhum momento fiz login com a minha conta "muriloschiler", somente cadastrei. Todas as tentativas de Login foram realizadas pelo "admin@admin.com"

**Comment by Luan-Cavalcante** [comment]
Consertado na nova tela de login.
