### ISSUE TITLE
BUG0035 - Estado do formulário de deleção está sendo mantido para diferentes repos

### ISSUE THREAD

**Issue by Luan-Cavalcante** [fga-eps-mds/2024.1-MeasureSoftGram-DOC#123]
<img width="1161" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNEcxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d61f0bdb9dba7938496d9912b7fe18b7322e3a21/image.png" alt="image.png" />

**Comment by AdneMoretti** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/20241-MeasureSoftGram-660b3c2cc830ad0f64db16b6/issues/fga-eps-mds/2024.1-MeasureSoftGram-DOC/123?planning-poker) with Zenhub @andremralves @brenno-silva @ciceroff @leonardomilv3 @Luan-Cavalcante @MorettiGS @muriloschiler @oEduardoAfonso
