### ISSUE TITLE
BUG005 - Corrigir bug de requisição em loop dos repositórios

### ISSUE THREAD

**Issue by Luan-Cavalcante** [fga-eps-mds/2024.1-MeasureSoftGram-DOC#56]
## Descrição
Ao buscar os repositórios de uma organização, a requisição para o /repositories fica em loop.

## Informações

Projeto: [measuresoftgram](https://github.com/fga-eps-mds/2024.1-MeasureSoftGram-Front)
Prints: 
<img width="578" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGdDQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c436108b1a1fa12ca76205275107dcf2c3e8192c/image.png" alt="image.png" />

## Critérios de Aceitação

- [ ] Ao clicar em visão geral de um produto deve fazer apenas a requisição necessária para listar os repositórios.
- [ ] Não deve ter loop infinito de requisições.

**Comment by AdneMoretti** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/20241-MeasureSoftGram-660b3c2cc830ad0f64db16b6/issues/fga-eps-mds/2024.1-MeasureSoftGram-DOC/56?planning-poker) with Zenhub @Luan-Cavalcante @ciceroff @MorettiGS @muriloschiler @leonardomilv3 @andremralves @brenno-silva @oEduardoAfonso
