### ISSUE TITLE
 BUG013 - Crash no Front ao adicionar um repositório no produto

### ISSUE THREAD

**Issue by chfleury** [fga-eps-mds/2024.1-MeasureSoftGram-DOC#66]
## Descrição
Crash no front ao adicionar um repositório no produto, o repositório é corretamente adiconado e persistido na base de dados, porém o front quebra, é necessário atualizar a página para sair dessa tela.
## Como reproduzir
Tentar adicionar algum repositório no produto.
## Comportamento esperado
É esperado que a tela não fique preta.
## Prints
<img width="1551" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVFVQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f6610f0b22226dab1c2e41186381e2f618139ca7/image.png" alt="image.png" />

**Comment by AdneMoretti** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/20241-MeasureSoftGram-660b3c2cc830ad0f64db16b6/issues/fga-eps-mds/2024.1-MeasureSoftGram-DOC/66?planning-poker) with Zenhub @andremralves @brenno-silva @ciceroff @leonardomilv3 @Luan-Cavalcante @MorettiGS @muriloschiler @oEduardoAfonso
