### ISSUE TITLE
BUG018 - Metrica de tests esperando uma lista com mais de um elemento no core no calculo de passed_tests (calculate_measures)

### ISSUE THREAD

**Issue by AdneMoretti** [fga-eps-mds/2024.1-MeasureSoftGram-DOC#90]

**Comment by chfleury** [comment]
Comportamento atual: so funciona ao passar uma lista de 2 ou mais números:<img width="1763" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemhiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d75847fb480a83991b098743ce5681d5b2d18058/image.png" alt="image.png" />

Erro que acontece quando manda apenas um número na metrica "tests" <img width="1565" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemxiQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2deeef474a3feb2f22305e9fdbb3745203b8d58/image.png" alt="image.png" />
