### ISSUE TITLE
BUG019 - Divisão por 0 no cálculo do CI_Feedback_Time e Team_Throughput

### ISSUE THREAD

**Issue by AdneMoretti** [fga-eps-mds/2024.1-MeasureSoftGram-DOC#92]
## Descrição

Atualmente o sistema não realiza o tratamento de erros para o caso das medidas de total_builds e total_issues estarem vazias para ou iguais a 0 (zero) para CI_feedback_time e Team_Throughput, respectivamente, ao realizar o cálculo de características e subcaracterísticas, o que impede o uso do Core para cálculo.

## Como reproduzir

Rode qualquer um dos comandos (`calculate` no CLI) ou realize qualquer fluxo que realiza o cálculo de características e subcaracterísticas com um valor zerado em total_builds ou total_issues. Será recebido um erro no console (para o caso da CLI) ou na web (para o caso do front) relatando que a divisão por zero não é possível.

## Comportamento esperado

O sistema deve tratar a possibilidade de ser recebido um valor zerado. Como o cálculo se trata de uma porcentagem baseado no valor total de total_builds ou total_issues, a ocorrência de um valor zerado para qualquer um deles implica que a porcentagem também será zero. Portanto, como a função em questão apenas retorna a porcentagem, é possível apenas retornar zero para o caso de qualquer um deles estarem iguais a zero.

**Comment by MorettiGS** [comment]
PR: https://github.com/fga-eps-mds/2024.1-MeasureSoftGram-Core/pull/5
