### ISSUE TITLE
Nova identidade visual

### ISSUE THREAD

**Issue by ciceroff** [fga-eps-mds/2024.1-MeasureSoftGram-DOC#94]

**Comment by AdneMoretti** [comment]
Criação de proposta de nova identidade visual para o sistema, incluindo a logo;

**Comment by AdneMoretti** [comment]
[Guia de Identidade Visual-2.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTk0Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5873d2d6c27456bb969d5fdecdf28f365a9abd5e/Guia%20de%20Identidade%20Visual-2.pdf)

Documento foi enviado ao cliente e está aguardando retorno

**Comment by AdneMoretti** [comment]
Documento final de IDV: [Guia de Identidade Visual MeasureSoftGram.pdf](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekhSQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c028ba78674fedd1ae2a8bb6755802ada9535b28/Guia%20de%20Identidade%20Visual%20MeasureSoftGram.pdf)
